name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browser-type
    attributes:
      label: Browser Type
      description: What web browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (specify below)
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What is the version of your web browser?
      placeholder: ex. 91.0.4472.124
    validations:
      required: true
  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If there are any error logs or console messages, please copy and paste them here.
      render: shell
      placeholder: Paste error logs here (if applicable)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/fantasyvball/fantasyvball.github.io/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
