export default {
    'AAC': ['Cincinnati', 'East Carolina', 'Houston', 'Memphis', 'SMU', 'South Fla.', 'Temple', 'Tulane', 'Tulsa', 'UCF', 'Wichita St.'],
    'ACC': ['Boston College', 'Clemson', 'Duke', 'Florida St.', 'Georgia Tech', 'Louisville', 'Miami (FL)', 'NC State', 'North Carolina', 'Notre Dame', 'Pittsburgh', 'Syracuse', 'Virginia', 'Virginia Tech', 'Wake Forest'],
    'ASUN': ['Austin Peay', 'Bellarmine', 'Central Ark.', 'Eastern Ky.', 'FGCU', 'Jacksonville', 'Jacksonville St.', 'Kennesaw St.', 'Liberty', 'Lipscomb', 'North Ala.', 'North Florida', 'Queens (NC)', 'Stetson'],
    'America East': ['Binghamton', 'Bryant', 'NJIT', 'New Hampshire', 'UAlbany', 'UMBC'],
    'Atlantic 10': ['Davidson', 'Dayton', 'Duquesne', 'Fordham', 'George Mason', 'George Washington', 'Loyola Chicago', 'Rhode Island', 'Saint Louis', 'VCU'],
    'Big 12': ['Baylor', 'Iowa St.', 'Kansas', 'Kansas St.', 'Oklahoma', 'TCU', 'Texas', 'Texas Tech', 'West Virginia'],
    'Big East': ['Butler', 'Creighton', 'DePaul', 'Georgetown', 'Marquette', 'Providence', 'Seton Hall', "St. John's (NY)", 'UConn', 'Villanova', 'Xavier'],
    'Big Sky': ['Eastern Wash.', 'Idaho', 'Idaho St.', 'Montana', 'Montana St.', 'Northern Ariz.', 'Northern Colo.', 'Portland St.', 'Sacramento St.', 'Weber St.'],
    'Big South': ['Campbell', 'Charleston So.', 'Gardner-Webb', 'High Point', 'Presbyterian', 'Radford', 'UNC Asheville', 'USC Upstate', 'Winthrop'],
    'Big Ten': ['Illinois', 'Indiana', 'Iowa', 'Maryland', 'Michigan', 'Michigan St.', 'Minnesota', 'Nebraska', 'Northwestern', 'Ohio St.', 'Penn St.', 'Purdue', 'Rutgers', 'Wisconsin'],
    'Big West': ['CSU Bakersfield', 'CSUN', 'Cal Poly', 'Cal St. Fullerton', 'Hawaii', 'Long Beach St.', 'UC Davis', 'UC Irvine', 'UC Riverside', 'UC San Diego', 'UC Santa Barbara'],
    'C-USA': ['Charlotte', 'FIU', 'Fla. Atlantic', 'Louisiana Tech', 'Middle Tenn.', 'North Texas', 'Rice', 'UAB', 'UTEP', 'UTSA', 'Western Ky.'],
    'CAA': ['Col. of Charleston', 'Delaware', 'Elon', 'Hampton', 'Hofstra', 'N.C. A&T', 'Northeastern', 'Stony Brook', 'Towson', 'UNCW', 'William & Mary'],
    'DI Independent': ['Chicago St.'],
    'Horizon': ['Cleveland St.', 'Green Bay', 'IUPUI', 'Milwaukee', 'Northern Ky.', 'Oakland', 'Purdue Fort Wayne', 'Robert Morris', 'Wright St.', 'Youngstown St.'],
    'Ivy League': ['Brown', 'Columbia', 'Cornell', 'Dartmouth', 'Harvard', 'Penn', 'Princeton', 'Yale'],
    'MAAC': ['Canisius', 'Fairfield', 'Iona', 'Manhattan', 'Marist', 'Niagara', 'Quinnipiac', 'Rider', "Saint Peter's", 'Siena'],
    'MAC': ['Akron', 'Ball St.', 'Bowling Green', 'Buffalo', 'Central Mich.', 'Eastern Mich.', 'Kent St.', 'Miami (OH)', 'NIU', 'Ohio', 'Toledo', 'Western Mich.'],
    'MEAC': ['Coppin St.', 'Delaware St.', 'Howard', 'Morgan St.', 'N.C. Central', 'Norfolk St.', 'South Carolina St.', 'UMES'],
    'MVC': ['Belmont', 'Bradley', 'Drake', 'Evansville', 'Illinois St.', 'Indiana St.', 'Missouri St.', 'Murray St.', 'Southern Ill.', 'UIC', 'UNI', 'Valparaiso'],
    'Mountain West': ['Air Force', 'Boise St.', 'Colorado St.', 'Fresno St.', 'Nevada', 'New Mexico', 'San Diego St.', 'San Jose St.', 'UNLV', 'Utah St.', 'Wyoming'],
    'NEC': ['Central Conn. St.', 'Fairleigh Dickinson', 'LIU', 'Merrimack', 'Sacred Heart', 'Saint Francis (PA)', 'St. Francis Brooklyn', 'Stonehill'],
    'OVC': ['Eastern Ill.', 'Lindenwood', 'Little Rock', 'Morehead St.', 'SIUE', 'Southeast Mo. St.', 'Southern Ind.', 'Tennessee St.', 'Tennessee Tech', 'UT Martin'],
    'Pac-12': ['Arizona', 'Arizona St.', 'California', 'Colorado', 'Oregon', 'Oregon St.', 'Southern California', 'Stanford', 'UCLA', 'Utah', 'Washington', 'Washington St.'],
    'Patriot': ['American', 'Army West Point', 'Bucknell', 'Colgate', 'Holy Cross', 'Lafayette', 'Lehigh', 'Loyola Maryland', 'Navy'],
    'SEC': ['Alabama', 'Arkansas', 'Auburn', 'Florida', 'Georgia', 'Kentucky', 'LSU', 'Mississippi St.', 'Missouri', 'Ole Miss', 'South Carolina', 'Tennessee', 'Texas A&M'],
    'SWAC': ['Alabama A&M', 'Alabama St.', 'Alcorn', 'Ark.-Pine Bluff', 'Bethune-Cookman', 'Florida A&M', 'Grambling', 'Jackson St.', 'Mississippi Val.', 'Prairie View', 'Southern U.', 'Texas Southern'],
    'SoCon': ['Chattanooga', 'ETSU', 'Furman', 'Mercer', 'Samford', 'The Citadel', 'UNC Greensboro', 'Western Caro.', 'Wofford'],
    'Southland': ['A&M-Corpus Christi', 'Houston Christian', 'Lamar University', 'McNeese', 'New Orleans', 'Nicholls', 'Northwestern St.', 'Southeastern La.', 'Tex. A&M-Commerce', 'UIW'],
    'Summit League': ['Denver', 'Kansas City', 'North Dakota', 'North Dakota St.', 'Omaha', 'Oral Roberts', 'South Dakota', 'South Dakota St.', 'St. Thomas (MN)', 'Western Ill.'],
    'Sun Belt': ['App State', 'Arkansas St.', 'Coastal Carolina', 'Ga. Southern', 'Georgia St.', 'James Madison', 'Louisiana', 'Marshall', 'Old Dominion', 'South Alabama', 'Southern Miss.', 'Texas St.', 'Troy', 'ULM'],
    'WAC': ['Abilene Christian', 'California Baptist', 'Grand Canyon', 'New Mexico St.', 'SFA', 'Sam Houston', 'Seattle U', 'Southern Utah', 'Tarleton St.', 'UT Arlington', 'UTRGV', 'Utah Tech', 'Utah Valley'],
    'WCC': ['BYU', 'Gonzaga', 'LMU (CA)', 'Pacific', 'Pepperdine', 'Portland', "Saint Mary's (CA)", 'San Diego', 'San Francisco', 'Santa Clara']
}
