name: Daily Update

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "45 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python and cache pip dependencies
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Update json
      run: python3 ./test/updateJson.py
    - name: Commit Changes
      run: |
        git config --global user.name "Yu-Chueh Wang"
        git config --global user.email "137755504+yuchuehw@users.noreply.github.com"
        git add ./test
        git commit -m 'source folder updated!' --allow-empty
        git push
